[Unit]
Wants=postgresql.service cloudbreak-snapshot-tracker.service
After=postgresql.service cloudbreak-snapshot-tracker.service
StartLimitIntervalSec=0

[Service]
TimeoutStartSec=infinity
ExecStartPre=
ExecStartPre=/usr/bin/python3 /opt/cloudbreak/deploy/wait-for-grpc.py
